
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import CartInitializer from "@/components/cart/CartInitializer";
import { Toaster } from 'react-hot-toast';
import { Suspense } from 'react';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(
    process.env.NODE_ENV === 'production' 
      ? 'https://yourmarket.com' 
      : 'http://localhost:3000'
  ),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
        <CartInitializer />
        
        {children}
        
        <Toaster position="bottom-right" />
      </AuthProvider>
      </body>
       </Suspense>
    </html>
  );
}
